// Mock transport for the dev toggle (settings.mock). No network, no API spend.
// Returns a deterministic scripted agent sequence so the whole loop, tool dispatch,
// write-back, persistence, and UI re-render are exercised:
//   call 1 -> web_search tool_call
//   call 2 -> web_fetch tool_call
//   call 3 -> set_day_plan tool_call (writes into the trip)
//   call 4 -> final answer text, no tool_calls

export async function mockChat(body) {
  await delay(250);
  const toolMessages = (body.messages || []).filter((m) => m.role === 'tool').length;
  const id = (n) => `call_${n}`;

  if (toolMessages === 0) {
    return openAI({
      content: 'I\'ll research options for your trip first.',
      tool_calls: [{ id: id(1), type: 'function', function: { name: 'web_search', arguments: JSON.stringify({ query: 'best things to do in destination top attractions' }) } }],
    });
  }
  if (toolMessages === 1) {
    return openAI({
      content: 'Let me read one of those results.',
      tool_calls: [{ id: id(2), type: 'function', function: { name: 'web_fetch', arguments: JSON.stringify({ url: 'https://example.com/top-attractions' }) } }],
    });
  }
  if (toolMessages === 2) {
    return openAI({
      content: 'Now I\'ll write the first day into your itinerary.',
      tool_calls: [{
        id: id(3), type: 'function',
        function: {
          name: 'set_day_plan',
          arguments: JSON.stringify({
            dayIndex: 0,
            items: [
              { type: 'lodging', title: 'Check in to hotel', time: '14:00', location: 'City center', notes: 'Mock item' },
              { type: 'activity', title: 'Walking tour of old town', time: '16:00', durationMin: 120, location: 'Old town', cost: 25 },
              { type: 'activity', title: 'Dinner at a local bistro', time: '19:30', location: 'Main square', cost: 40 },
            ],
          }),
        },
      }],
    });
  }
  // final answer
  return openAI({
    content: 'I\'ve planned your first day: check-in, an afternoon walking tour, and dinner at a local bistro. ' +
      'This was generated by the **mock transport** (Settings → Mock transport), so no real API calls were made. ' +
      'Disable the mock toggle to use live Ollama. Sources: https://example.com/top-attractions',
    tool_calls: undefined,
  });
}

export async function mockWebSearch({ query }) {
  await delay(200);
  return {
    results: [
      { title: 'Top attractions in destination', url: 'https://example.com/top-attractions', content: 'A mock search result for: ' + query + '. Lists museums, food markets, and viewpoints.' },
      { title: 'Travel guide 2026', url: 'https://example.com/guide', content: 'Mock guide with transport tips and seasonal advice.' },
    ],
  };
}

export async function mockWebFetch() {
  await delay(200);
  return { title: 'Top attractions in destination', content: 'Mock page content: the old town walking route takes about 2 hours. Bistros open at 18:00. Average dinner cost is 35-45 in local currency.', links: ['https://example.com/old-town'] };
}

function openAI({ content, tool_calls }) {
  return {
    choices: [{ index: 0, message: { role: 'assistant', content: content ?? null, tool_calls }, finish_reason: tool_calls ? 'tool_calls' : 'stop' }],
    usage: { prompt_tokens: 0, completion_tokens: 0, total_tokens: 0 },
  };
}

function delay(ms) { return new Promise((r) => setTimeout(r, ms)); }